server_info:
  address: "http://127.0.0.1:6164"
  specification:
    input:
      - image
    output:
      - list
      - json
      - image
  name: "test app"
  invitation_message: "send image"
  passphrase: "passphrase"
port: 6164
host: "0.0.0.0"
# consul:
#   host: 127.0.0.1
#   port: 8500
ds_model_config:
  model_name: 'cihp_ds_model.py'
  config: {}
